### ISSUE TITLE
Circular dependency detection broken?

### ISSUE THREAD

**Issue by pigulla** [hapijs/topo#27]
Maybe I'm just not seeing the forest for the trees, but what am I doing wrong?

With `topo` 2.0.2:
```js
const Topo = require('topo');

const topo = new Topo();

// set up a circular dependency
topo.add('A', { after: ['B'] });
topo.add('B', { after: ['A'] });

console.dir(topo.nodes);
// [ 'A', 'B' ]
```

Shouldn't this throw an exception?

**Comment by devinivy** [comment]
The labels are not based upon the value of the node, but rather the group.  Check this out instead,

```js
const Topo = require('topo');

const topo = new Topo();

// set up a circular dependency
topo.add('A-node', { after: ['B'], group: 'A' });
topo.add('B-node', { after: ['A'], group: 'B' }); // Throws
```

**Comment by pigulla** [comment]
Ah, I see. So I need to add a "dummy group" to each node (assuming there is no other logical grouping)?

**Comment by devinivy** [comment]
Yup, exactly!  The node itself can be anything– an object, number, etc.  The group is the label actually used for sorting.
