### ISSUE TITLE
Topo and uglify-js not working

### ISSUE THREAD

**Issue by jfstephe** [hapijs/topo#38]
Hi,
The issue I get is in my aurelia/SystemJs application when bundling the application for production uglify-js is run against my app and all dependencies.

The error I see is:

Error: SyntaxError: Unexpected token: punc ({)

which I tracked down to uglify-js interacting with topo or it's dependencies. I *don't think this is an issue with topo* per se, but I'm raising this for awareness and to try and help other so they don't waste their time like I did. The workaround for me was to create a separate bundle that isn't minified, in the aurelia bundle config:

    "dist/third-party-non-minify": {
      "includes": [
        'topo'
      ],
      "options": {
        "sourceMaps": true,
        "inject": true,
        "minify": false,
        "depCache": false,
        "rev": true
      }
    }

**Comment by devinivy** [comment]
Just as a hunch: could be related to the fact that topo is written using features of JS supported by node, but not recognized by uglify (i.e. ES6 features—your error looks like it might be choking on an arrow function `({ something }) => something`).
