### ISSUE TITLE
Sort result does not correct

### ISSUE THREAD

**Issue by masquevil** [hapijs/topo#59]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 
* *module version with issue*: 4.0.1
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): chrome
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
x = new Topo.Sorter();
x.add('a', { before: ['b', 'c'] });
x.add('b');
x.add('c', { before: ['b'] });
x.add('e', { before: ['c'] });
console.log(x.nodes);
y = new Topo.Sorter();
y.add('d', { before: ['c'] });
y.merge(x);
console.log(y.nodes);
```

#### What was the result you got?
```js
["a", "b", "c", "e"]
["d", "a", "b", "c", "e"]
```

#### What result did you expect?
```js
["a", "e", "c", "b"]
["d", "a", "e", "c", "b"]
```

**Comment by devinivy** [comment]
The nodes are sorted by their `group`, not the values themselves.  Give this a whirl:
```js
x = new Topo.Sorter();
x.add('a', { before: ['b', 'c'], group: 'a' });
x.add('b', { group: 'b' });
x.add('c', { before: ['b'], group: 'c' });
x.add('e', { before: ['c'], group: 'e' });
console.log(x.nodes);
y = new Topo.Sorter();
y.add('d', { before: ['c'], group: 'd' });
y.merge(x);
console.log(y.nodes);
```

**Comment by masquevil** [comment]
Thank you!
